"""restaurant table

Revision ID: 7cd21aed1e65
Revises: 
Create Date: 2025-12-10 21:25:21.865644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd21aed1e65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('restaurant_key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visiting_frequency', sa.String(length=30), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('open_late', sa.Boolean(), nullable=False),
    sa.Column('open_early', sa.Boolean(), nullable=False),
    sa.Column('have_i_been', sa.Boolean(), nullable=False),
    sa.Column('need_reservation', sa.Boolean(), nullable=False),
    sa.Column('good_drinks', sa.Boolean(), nullable=False),
    sa.Column('good_desserts', sa.Boolean(), nullable=False),
    sa.Column('study_spot', sa.Boolean(), nullable=False),
    sa.Column('veg_friendly', sa.Boolean(), nullable=False),
    sa.Column('dairy_free_items', sa.Boolean(), nullable=False),
    sa.Column('quick', sa.Boolean(), nullable=False),
    sa.Column('lunch_spot', sa.Boolean(), nullable=False),
    sa.Column('order_online', sa.Boolean(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('dress_attire', sa.String(), nullable=False),
    sa.Column('opinion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('restaurant_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('location',
    sa.Column('location_key', sa.Integer(), nullable=False),
    sa.Column('restaurant_key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['restaurant.name'], ),
    sa.ForeignKeyConstraint(['restaurant_key'], ['restaurant.restaurant_key'], ),
    sa.PrimaryKeyConstraint('location_key')
    )
    op.create_table('photos',
    sa.Column('file_key', sa.Integer(), nullable=False),
    sa.Column('restaurant_key', sa.Integer(), nullable=False),
    sa.Column('file_link', sa.String(), nullable=False),
    sa.Column('photo_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_key'], ['restaurant.restaurant_key'], ),
    sa.PrimaryKeyConstraint('file_key'),
    sa.UniqueConstraint('file_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    op.drop_table('location')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
